# Generated by Django 2.2.6 on 2019-11-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='linkimage',
            field=models.TextField(verbose_name='link to image'),
        ),
    ]
