# Generated by Django 2.2.6 on 2019-11-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20191105_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(error_messages={'unique': 'Movie with this title already exists'}, max_length=50, unique=True, verbose_name='Name of movie'),
        ),
    ]
