# Generated by Django 2.2.6 on 2019-12-26 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20191226_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Series',
        ),
        migrations.AlterField(
            model_name='movie',
            name='linkname',
            field=models.CharField(error_messages={'unique': 'Movie with this link already exists'}, max_length=100, null=True, unique=True, verbose_name='Kinopoisk id of series'),
        ),
        migrations.CreateModel(
            name='seriesComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Display on screen?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.series', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Series_Comment',
                'verbose_name_plural': 'Series_Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
